# PBS configuration
queue: expressbw
project: e14
walltime: 01:00:00
jobname: ryf8_kds50
ncpus: 252
mem: 500GB

shortpath: /short/e14

runspersub: 1
restart_freq: 1

# Model configuration
model: access-om2
input: /short/public/access-om2/input_38570c62/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/public/access-om2/bin/yatm_af01d117.exe
      input: /short/public/access-om2/input_38570c62/yatm_1deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/public/access-om2/bin/fms_ACCESS-OM_99168b44.x
      input:  
              - /g/data1/ua8/MOM/initial_conditions/WOA/10_KDS50
              - /g/data1/ua8/MOM/grids/10/topog/KDS50
              - /g/data/ua8/MOM/salinity_restoring/10
              - /short/public/access-om2/input_38570c62/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /short/public/access-om2/bin/cice_auscom_360x300_24p_0981e598.exe
      input: /short/public/access-om2/input_38570c62/cice_1deg
      ncpus: 24

platform:
    nodesize: 28

# Misc
runlog: True
stacksize: unlimited
collate_walltime: 1:00:00
collate_queue: express
collate_ncpus: 1
collate_mem: 12GB
collate_flags: -n4 -z -m -r
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread -W umask=027
# postscript: sync_output_to_gdata.sh
